// drzewo
%(x)f,%(y)f,%(zw)f 0,0,0 1,0 end
%(x)f,%(yh)f,%(zw)f 0,0,0 1,1 end
%(x)f,%(y)f,%(zmw)f 0,0,0 0,0 end

%(x)f,%(yh)f,%(zw)f 0,0,0 1,1 end
%(x)f,%(y)f,%(zmw)f 0,0,0 0,0 end
%(x)f,%(yh)f,%(zmw)f 0,0,0 0,1 end

%(xw)f,%(y)f,%(z)f 0,0,0 1,0 end
%(xw)f,%(yh)f,%(z)f 0,0,0 1,1 end
%(xmw)f,%(y)f,%(z)f 0,0,0 0,0 end

%(xw)f,%(yh)f,%(z)f 0,0,0 1,1 end
%(xmw)f,%(y)f,%(z)f 0,0,0 0,0 end
%(xmw)f,%(yh)f,%(z)f 0,0,0 0,1 end
